name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      # OPTIONAL: run tests
      # - name: Test
      #   run: npm test

      # ---- Zip the repo (root contains package.json & server.js) ----
      - name: Create deployment package
        run: zip -r build.zip . -x ".git/*"

      # ---- Deploy with publish profile (ZipDeploy) ----
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: iot-socket-studio-app           # <--- EXACT Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build.zip
          enable-oryx-build: true

      # (Optional) Health check
      - name: Check health endpoint
        run: |
          echo "Waiting for warmup..."
          sleep 10
          curl -fsS https://iot-socket-studio-app.azurewebsites.net/healthz