# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - iot-socket-studio-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # Optional: only if you actually have a build step or tests
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test --if-present

      # Create a clean deployment artifact (exclude VCS)
      - name: Create deployment package
        run: zip -r build.zip . -x ".git/*" ".github/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Warm up Kudu (avoid SCM restart race) and wait a bit
      - name: Warm up Kudu & wait
        env:
          APP_NAME: iot-socket-studio-app
        run: |
          echo "Warming up SCM..."
          curl -s https://$APP_NAME.scm.azurewebsites.net/api/health || true
          sleep 15

      # First deploy attempt (continue-on-error so we can retry)
      - name: Deploy to Azure Web App (attempt 1)
        id: deploy1
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'iot-socket-studio-app'
          slot-name: 'Production'
          package: build.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB5C0712C14B4CF289AE582F466BEF53 }}
          enable-oryx-build: true
        continue-on-error: true

      # Retry once if SCM was restarting
      - name: Retry after delay (if needed)
        if: steps.deploy1.outcome == 'failure'
        run: |
          echo "First deploy failed, waiting 20s to avoid SCM restart conflict..."
          sleep 20

      - name: Deploy to Azure Web App (attempt 2)
        if: steps.deploy1.outcome == 'failure'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'iot-socket-studio-app'
          slot-name: 'Production'
          package: build.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB5C0712C14B4CF289AE582F466BEF53 }}
          enable-oryx-build: true

      # Optional: health check
      - name: Check health endpoint
        run: |
          echo "Waiting for warmup..."
          sleep 10
          curl -fsS https://iot-socket-studio-app.azurewebsites.net/healthz