deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    # Warm up Kudu (avoid SCM restart race) and wait a bit
    - name: Warm up Kudu & wait
      env:
        APP_NAME: iot-socket-studio-app
      run: |
        echo "Warming up SCM..."
        curl -s https://$APP_NAME.scm.azurewebsites.net/api/health || true
        sleep 15

    # First deploy attempt (continue-on-error so we can retry if Kudu restarts)
    - name: Deploy to Azure Web App (attempt 1)
      id: deploy1
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'iot-socket-studio-app'
        slot-name: 'Production'
        package: build.zip
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB5C0712C14B4CF289AE582F466BEF53 }}
        enable-oryx-build: true
      continue-on-error: true

    - name: Retry after delay (if needed)
      if: steps.deploy1.outcome == 'failure'
      run: |
        echo "First deploy failed, waiting 20s to avoid SCM restart conflict..."
        sleep 20

    - name: Deploy to Azure Web App (attempt 2)
      if: steps.deploy1.outcome == 'failure'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'iot-socket-studio-app'
        slot-name: 'Production'
        package: build.zip
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB5C0712C14B4CF289AE582F466BEF53 }}
        enable-oryx-build: true

    # Poll the health endpoint for up to ~3 minutes
    - name: Poll /healthz until ready
      shell: bash
      run: |
        APP_URL="https://iot-socket-studio-app.azurewebsites.net/healthz"
        echo "Polling $APP_URL ..."
        for i in {1..18}; do
          code=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL" || true)
          if [ "$code" = "200" ]; then
            echo "Health OK (200)"
            exit 0
          fi
          echo "Not ready yet (HTTP $code). Wait and retry..."
          sleep 10
        done
        echo "App did not become healthy in time"
        exit 1